version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: master
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    target-branch: master
