name: setup php

description: "Setup the php composer env"

inputs:
  php-version:
    required: true
    description: 'PHP version to use'
  laravel-version:
    required: false
    description: 'Laravel major version'
    default: ''

runs:
  using: composite
  steps:
    - name: Set Laravel & Testbench version constraints
      if: inputs.laravel-version != ''
      shell: bash
      run: |
        composer require \
          "laravel/framework:^${{ inputs.laravel-version }}.0" \
          --no-update --no-interaction

    - name: Cache php composer
      id: cache-composer
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      env:
        cache-name-php: cache-composer
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ inputs.php-version }}-laravel${{ inputs.laravel-version }}-build-${{ env.cache-name-php }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ inputs.php-version }}-laravel-${{ inputs.laravel-version }}-build-${{ env.cache-name-php }}-
          ${{ runner.os }}-php-${{ inputs.php-version }}-laravel-${{ inputs.laravel-version }}-
          ${{ runner.os }}-php-${{ inputs.php-version }}-
          ${{ runner.os }}-

    - name: Install php dependencies
      if: steps.cache-composer.outputs.cache-hit != 'true'
      shell: bash
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
